### PR TITLE
Cmake

### PR DESCRIPTION
**Pull request by DoumanAsh**

### CODE REVIEW

**Comment by DoumanAsh** [comment]
@alyssais
Can I ask you to verify how cross-compilation works with cmake?

**Comment by alyssais** [comment]
> @alyssais
> Can I ask you to verify how cross-compilation works with cmake?

Will do this shortly.

As an aside, you might want to consider using git subtree to add the
opus sources.  It would include the opus sources in this repository
(rather than an annoying seperate thing like a submodule), but still
preserve the history.

**Comment by alyssais** [comment]
>> Can I ask you to verify how cross-compilation works with cmake?

Cross-compiling works for me with this.

**Comment by DoumanAsh** [comment]
Cool, thanks.
I'll be preparing `0.3` with cmake tomorrow then

**Pull request merged**
