### PR TITLE
Fix libopus build on 64-bit linux

### LINKED ISSUE #9: Use LIBRARY_OUTPUT_DIRECTORY
https://cmake.org/cmake/help/latest/prop_tgt/LIBRARY_OUTPUT_DIRECTORY.html

### PR DESCRIPTION
**Pull request by Ralith**
Fixes #9

### CODE REVIEW

**Comment by Ralith** [comment]
Ah, I'll look into that. I'm pretty mystified by why Ubuntu is failing; different cmake versions maybe?

**Comment by Ralith** [comment]
Sure, that's fine too. I'm just wrapping up for the night here, but I can report back with test results tomorrow morning.

**Comment by DoumanAsh** [comment]
@Ralith I made commit which overrides output directory for lib. Please try to verify it on your system, if it works

**Comment by Ralith** [comment]
Works great, thanks!

**Pull request merged**
